apiVersion: v1
kind: Secret
metadata:
  name: devops-api
type: Opaque
data:
  GITLAB_TOKEN: {{ .Values.devopsApi.GITLAB_TOKEN | quote }}
  POSTGRES_PASSWORD: {{ .Values.devopsApi.POSTGRES_PASSWORD | quote }}
  POSTGRES_USER: {{ .Values.devopsApi.POSTGRES_USER | quote }}