import struct
import time
import os
import json
import base64   
from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305

def convert_hex_to_key(hex_string):
    """
    Decodes a 64-character hexadecimal string back into 32 bytes.
    Validates length to ensure cryptographic integrity before use.
    """
    try:
        key_bytes = bytes.fromhex(hex_string)
        if len(key_bytes) != 32:
            raise ValueError("Invalid key length: Must be exactly 32 bytes.")
        return key_bytes
    except ValueError as e:
        print(f"Key Conversion Error: {e}")
        return None
    
def generate_branca_token(payload, key_32_bytes):
    version = b'\xBA' 
    
    timestamp = struct.pack(">I", int(time.time())) 
    
    nonce = os.urandom(12) 
    
    plain_text = json.dumps(payload).encode('utf-8')
    
    aead = ChaCha20Poly1305(key_32_bytes)
    
    associated_data = version + timestamp + nonce
    
    cipher_text = aead.encrypt(nonce, plain_text, associated_data)
    
    binary_token = version + timestamp + nonce + cipher_text
    
    return base64.urlsafe_b64encode(binary_token).decode('utf-8')


def main():
    user_data = {
        "groups": "infrastructure.dns",
        "user_id": 123, 
        "zones": ["example.com"],
        "permissions": ["read", "write"],
        "iat": int(time.time()),
        "exp": int(time.time()) + 3600  # Expires in 1 hour.
    }

    # The key MUST be exactly 32 bytes
    # The key was randomly generated by the function generate_secure_32_byte_key and converted to hexadecimal using convert_key_to_hex.

    secure_key_bytes = "6242a422c9964c48ea61bc11ba412ad7a7e96cb1a548af3dc25ca9cdb3a2f0a2"
    token = generate_branca_token(user_data, convert_hex_to_key(secure_key_bytes))
    print(f"Branca Token: {token}")

if __name__ == "__main__":
    main()    