Vagrant.configure("2") do |config|
  config.vm.define "srv-infrastructure-postgresql-master-01", autostart: true do |jenkins|
    jenkins.vm.box = "base-ubuntu-1.0.0"
    jenkins.vm.hostname = 'srv-infrastructure-postgresql-master-01'

    jenkins.vm.network "public_network", use_dhcp_assigned_default_route: true, bridge: "enp7s0", ip: "172.21.5.158"
    jenkins.vm.synced_folder "/work/", "/work"
    jenkins.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 1024]
        v.customize ["modifyvm", :id, "--name", "srv-infrastructure-postgresql-master-01"]
    end
  end
end