- name: output the global playbook 'ansible_ssh_user' variable
  ansible.builtin.debug: 
    var: ansible_ssh_user

- name: output the global playbook 'ansible_ssh_pass' variable
  ansible.builtin.debug: 
    var: ansible_ssh_pass

- name: output the global playbook 'ansible_ssh_common_args' variable
  ansible.builtin.debug: 
    var: ansible_ssh_common_args

- name: output the global playbook 'global_database.username' variable
  ansible.builtin.debug: 
    var: global_database.username

- name: output the global playbook 'global_database.password' variable
  ansible.builtin.debug: 
    var: global_database.password

- name: Create secrets dir 
  file: 
    path: "/root/secrets"
    state: directory

- name: Add secrets mount with local variables - jinja
  ansible.builtin.template:
    dest: /root/secrets/secrets
    src: secrets/secrets.j2
    mode: '0644'
    owner: root
    group: root