version: "3"

services:
  srv-ldap-01:
    container_name: srv-ldap-01
    hostname: srv-ldap-01
    image: bitnami/openldap:2.5.17
    environment:
      - LDAP_ADMIN_USERNAME=admin 
      - LDAP_PORT_NUMBER=389 
      - LDAP_ADMIN_PASSWORD='JbBmKx#lK@ZX4*amqd5l' 
      - LDAP_ROOT=dc=devops-db,dc=info 
      - LDAP_ADMIN_DN=CN=admin,DC=devops-db,DC=info 
      - LDAP_EXTRA_SCHEMAS=cosine,inetorgperson,nis,memberof 
    ports:
      - "389:389/tcp"
      - "636:636/tcp"
    volumes:
      - /work/ldap/memberof.ldif:/bitnami/openldap/memberof.ldif
      - /work/ldap/memberof.ldif:/opt/bitnami/openldap/etc/schema/memberof.ldif
    restart: unless-stopped
    networks:
      - ldap_bridge
networks:
  ldap_bridge:
    name: ldap_bridge
    driver: bridge
