Vagrant.configure("2") do |config|
  config.vm.define "srv-ldap-01" do |openldap|
    openldap.vm.box = "bento/ubuntu-22.04"
    openldap.vm.hostname = 'srv-ldap-01'

    openldap.vm.network "public_network", use_dhcp_assigned_default_route: true, bridge: "enp7s0", ip: "172.21.5.150"
    openldap.vm.synced_folder "/work/openldap/", "/work"
    openldap.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 1024]
        v.customize ["modifyvm", :id, "--name", "srv-ldap-01"]
    end
  end
end
