apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: totp-api-canary
  namespace: argocd
spec:
  project: totp-api

  sources:
    # Chart (Nexus)
    - repoURL: https://nexus.devops-db.internal/repository/helm-devops-db/
      chart: totp-api
      targetRevision: 1.0.7
      helm:
        valueFiles:
          - $repo-app-values/envs/staging/values-canary.yaml

    # Values (GitLab)
    - repoURL: https://gitlab.devops-db.internal/infrastructure/argocd/applications/totp-api.git
      targetRevision: HEAD
      ref: repo-app-values

  destination:
    server: https://kubernetes.default.svc
    namespace: devops-api-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true