Vagrant.configure("2") do |config|
  config.vm.define "srv-infrastructure-microk8-master-01", autostart: true do |microk8|
    microk8.vm.box = "base-ubuntu-1.0.0"
    microk8.vm.hostname = 'srv-infrastructure-microk8-master-01'

    microk8.vm.network "public_network", use_dhcp_assigned_default_route: true, bridge: "enp7s0", ip: "172.21.5.156"
    microk8.vm.synced_folder "/work/", "/work"
    microk8.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 4096]
        v.customize ["modifyvm", :id, "--name", "srv-infrastructure-microk8-master-01"]
    end
  end
end