apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-canary
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
{{- if not .Values.rollout.enabled }}
  selector:
    app: {{ .Release.Name }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP