import hmac
import hashlib
import base64
import json
import time


def base64url_encode(data):
    """Encodes data to Base64URL format without padding."""
    return base64.urlsafe_b64encode(data).rstrip(b'=').decode('utf-8')

def generate_manual_jwt(payload, secret_key):
    # 1. Header (Standard for HS256)
    header = {"alg": "HS256", "typ": "JWT"}
    encoded_header = base64url_encode(json.dumps(header).encode('utf-8'))
    
    # 2. Payload
    encoded_payload = base64url_encode(json.dumps(payload).encode('utf-8'))
    
    # 3. Signature
    signing_input = f"{encoded_header}.{encoded_payload}".encode('utf-8')
    signature = hmac.new(
        secret_key.encode('utf-8'),
        signing_input,
        hashlib.sha256
    ).digest()
    encoded_signature = base64url_encode(signature)
    
    return f"{encoded_header}.{encoded_payload}.{encoded_signature}"

def main():
    user_data = {
        "groups": "infrastructure.dns",
        "user_id": 123, 
        "zones": ["example.com"],
        "permissions": ["read", "write"],
        "iat": int(time.time()),
        "exp": int(time.time()) + 3600  # Expires in 1 hour.
    }

    # The key can be any value, but by default in these examples, I will use a 32-byte key.
    # The key was randomly generated by the function generate_secure_32_byte_key and converted to hexadecimal using convert_key_to_hex.
    secure_key_bytes = "6242a422c9964c48ea61bc11ba412ad7a7e96cb1a548af3dc25ca9cdb3a2f0a2"
    print(f"JWT Token: {generate_manual_jwt(user_data, secure_key_bytes)}")

if __name__ == "__main__":
    main()    