Vagrant.configure("2") do |config|
  config.vm.define "srv-infrastructure-gitlab-master-01" do |gitlab|
    gitlab.vm.box = "bento/ubuntu-22.04"
    gitlab.vm.hostname = 'srv-infrastructure-gitlab-master-01'

    gitlab.vm.network "public_network", use_dhcp_assigned_default_route: true, bridge: "enp7s0", ip: "172.21.5.153"
    gitlab.vm.synced_folder "/work/", "/work"
    gitlab.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 4096]
        v.customize ["modifyvm", :id, "--name", "srv-infrastructure-gitlab-master-01"]
    end
  end
end