---
version: 1
group: infrastructure
tech: dns
service: devops-db.internal
description: Blueprint with DNS zones from devops-db.internal
nameservers:
  - name: ns1.devops-db.internal
    class: IN
    type: A
    destination: 172.21.5.72
admin: admin.devops-db.internal
serial_number: 2022122800
time_to_refresh: 12h
time_to_retry: 15m
time_to_expire: 3w
minimum_ttl: 2h
zones:
  - host: srv-consul-01 
    class: IN
    type: A
    destination: 172.21.5.152
  - host: gitlab
    class: IN
    type: A
    destination: 172.21.5.153
  - host: registry
    class: IN
    type: A
    destination: 172.21.5.75
  - host: jenkins
    class: IN
    type: A
    destination: 172.21.5.70
  - host: ldapman
    class: IN
    type: A
    destination: 172.21.5.72
  - host: devpi
    class: IN
    type: A
    destination: 172.21.5.160
