---
version: 1
group: infrastructure
tech: dns
service: lab.devops-db.com
description: Blueprint with DNS zones from lab.devops-db.com
nameservers:
  - name: ns1.lab.devops-db.com
    class: IN
    type: A
    destination: 172.21.5.72
admin: admin.lab.devops-db.com
serial_number: 2022122800
time_to_refresh: 12h
time_to_retry: 15m
time_to_expire: 3w
minimum_ttl: 2h
zones:
  - host: srv-consul-01 
    class: IN
    type: A
    destination: 172.21.5.152
  - host: gitlab
    class: IN
    type: A
    destination: 172.21.5.153
  - host: registry
    class: IN
    type: A
    destination: 172.21.5.75
  - host: jenkins
    class: IN
    type: A
    destination: 172.21.5.70
