import os
import time
import json         
import base64
from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305

def convert_hex_to_key(hex_string):
    """
    Decodes a 64-character hexadecimal string back into 32 bytes.
    Validates length to ensure cryptographic integrity before use.
    """
    try:
        key_bytes = bytes.fromhex(hex_string)
        if len(key_bytes) != 32:
            raise ValueError("Invalid key length: Must be exactly 32 bytes.")
        return key_bytes
    except ValueError as e:
        print(f"Key Conversion Error: {e}")
        return None

def base64url_encode(data):
    """Encodes data to Base64URL format without padding."""
    return base64.urlsafe_b64encode(data).rstrip(b'=').decode('utf-8')


def generate_paseto_v4_local(payload, key_32_bytes):
    # Header for v4.local
    header = b"v4.local."
    
    # Payload must be bytes (usually JSON)
    plain_text = json.dumps(payload).encode('utf-8')
    
    # Nonce (Adjusted to 12 bytes to match the available AEAD class)
    nonce = os.urandom(12)
    
    # Initialize Cipher using the compatible ChaCha20Poly1305
    aead = ChaCha20Poly1305(key_32_bytes)
    
    # The header acts as 'Additional Authenticated Data' (AAD)
    # This ensures the header cannot be tampered with
    cipher_text = aead.encrypt(nonce, plain_text, header)
    
    # Format: header + base64(nonce + cipher_text)
    token_body = base64url_encode(nonce + cipher_text)
    return f"v4.local.{token_body}"

# Usage (Requires a 32-byte key)

def main():
    user_data = {
        "groups": "infrastructure.dns",
        "user_id": 123, 
        "zones": ["example.com"],
        "permissions": ["read", "write"],
        "iat": int(time.time()),
        "exp": int(time.time()) + 3600  # Expires in 1 hour.
    }

    # The key MUST be exactly 32 bytes
    # The key was randomly generated by the function generate_secure_32_byte_key and converted to hexadecimal using convert_key_to_hex.

    secure_key_bytes = "6242a422c9964c48ea61bc11ba412ad7a7e96cb1a548af3dc25ca9cdb3a2f0a2"

    print(f"Paseto Token: {generate_paseto_v4_local(user_data, convert_hex_to_key(secure_key_bytes))}")


if __name__ == "__main__":
    main()    