apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: default
  name: vault-static-secret-jenkins
spec:
  vaultAuthRef: static-auth-jenkins
  mount: secret
  type: kv-v2
  path: infrastructure/jenkins/test-secret01
  refreshAfter: 10s
  destination:
    create: true
    name: jenkins-test-secret01
  rolloutRestartTargets:
  - kind: Deployment
    name: vault_jenkins
