apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: default
  name: vault-static-secret-certificates-devops-db
spec:
  vaultAuthRef: static-auth-jenkins
  mount: secret
  type: kv-v2
  path: infrastructure/certificates/devops-db
  refreshAfter: 10s
  destination:
    create: true
    name: certificates-devops-db
  rolloutRestartTargets:
  - kind: Deployment
    name: vault_certificates
