{{- if .Values.secrets }}
{{- range $name, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-%s" $.Release.Name $.Chart.Name $name }}
  namespace: {{ $.Release.Namespace }}
type: {{ $secret.type }}
data:
{{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
{{- end }}