version: "3"

services:
  jenkins:
    container_name: srv-jenkins-01
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - /Users/fausto.branco/OneDrive/Work/Jenkins/jenkins-server-01:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - jenkins_bridge
networks:
  jenkins_bridge:
    name: jenkins_bridge
    driver: bridge
