{{- if .Values.global.secrets }}
{{- range $name, $secret := .Values.global.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
type: {{ $secret.type | default "Opaque" }}
data:
{{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
{{- end }}