- hosts: "{{ cluster_group | default('none') }}"
  become: true
  roles:
   - test_secret
  vars_files:
    - /work/external/global_vars/global_access.yaml
  gather_facts: True
#  
- import_playbook: /work/external/playbooks/certificate/certificate.yaml
  vars:
    cluster_group: { cluster_group }
 