apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
{{- range $key, $value := .Values.configmap.dbHosts }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
#{{- range $key, $value := .Values.configmap.configs }}
#  {{ $key }}: {{ $value | quote }}
#{{- end }}