Vagrant.configure("2") do |config|
  config.vm.define "srv-devpi-01" do |srvdevpi|
    srvdevpi.vm.box = "bento/ubuntu-22.04"
    srvdevpi.vm.hostname = 'srv-devpi-01'

    srvdevpi.vm.network "public_network", use_dhcp_assigned_default_route: true, bridge: "enp7s0", ip: "172.21.5.160"
    srvdevpi.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 1024]
        v.customize ["modifyvm", :id, "--name", "srv-devpi-01"]
    end
  end
end
