role: stable

traffic:
  stable: 90
  canary: 10

gateway:
  enabled: true
  name: devops-api-stable-gateway
  namespace: devops-api
  host: devops-api.devops-db.internal

replicaCount: 1
image:
  repository: nexus.devops-db.internal/devops_images/devops-api
  pullPolicy: IfNotPresent
  tag: "1.1.1"

imagePullSecrets:
  - name: nexus-registry

devopsApi:
  GITLAB_TOKEN: Z2xwYXQtdWN0WEhTcDN6cW5MQUsxQmJSMXRhRzg2TVFwMU9qWUguMDEuMHcxaXJydWly
  POSTGRES_PASSWORD: MTIzNHF3ZXI=
  POSTGRES_USER: ZGV2b3BzX2FwaQ==

autoscaling:
  enabled: false

service:
  type: ClusterIP
  port: 80
  internalPort: 8080

env:
  GITLAB_URL: https://gitlab.devops-db.internal
  DEVOPSAPI_VERSION: v1.1.1

configmap:
  dbHosts:
    customers_dev: postgresql.devops-db.internal
    inventory_dev: postgresql.devops-db.internal
    orders_dev: postgresql.devops-db.internal
    payment_dev: postgresql.devops-db.internal
    reporting_dev: postgresql.devops-db.internal
    customers_staging: postgresql.devops-db.internal
    inventory_staging: postgresql.devops-db.internal
    orders_staging: postgresql.devops-db.internal
    payment_staging: postgresql.devops-db.internal
    reporting_staging: postgresql.devops-db.internal
    customers_prod: postgresql.devops-db.internal
    inventory_prod: postgresql.devops-db.internal
    orders_prod: postgresql.devops-db.internal
    payment_prod: postgresql.devops-db.internal
    reporting_prod: postgresql.devops-db.internal


