- name: Include vars files.
  ansible.builtin.include_vars: "{{ item }}"
  with_items:
    - /work/external/global_vars/global_database.yaml
    - /work/external/global_vars/global_ldap.yaml 

- name: output the global playbook 'ansible_ssh_user' variable
  ansible.builtin.debug: 
    var: ansible_ssh_user

- name: output the global playbook 'ansible_ssh_pass' variable
  ansible.builtin.debug: 
    var: ansible_ssh_pass

- name: output the global playbook 'ansible_ssh_common_args' variable
  ansible.builtin.debug: 
    var: ansible_ssh_common_args

- name: output the global playbook 'global_database.username' variable
  ansible.builtin.debug: 
    var: global_database.username

- name: output the global playbook 'global_database.password' variable
  ansible.builtin.debug: 
    var: global_database.password

- name: Create secrets dir 
  file: 
    path: "/root/secrets"
    state: directory

- name: Add secrets mount with local variables - jinja
  ansible.builtin.template:
    dest: /root/secrets/secrets
    src: /work/external/global_templates/secrets/secrets.j2
    mode: '0644'
    owner: root
    group: root

#######################################################################################################################

- name: Configure LDAP  
  include_tasks: /work/external/playbooks/ldap/roles/configure_ldap/tasks/main.yaml
 